/** Opaque IDs are UUID v4 strings generated by the connection service. */
export type ConnectionId = string;
export type FolderId = string;

export type Authentication =
  | { type: 'password'; hasStoredPassword: boolean }
  | { type: 'privateKey'; privateKeyPath: string; hasStoredPassphrase: boolean }
  | { type: 'agent' };

export interface AgentAccessPolicy {
  enabled: boolean;
  allowReadFiles: boolean;
  allowWriteFiles: boolean;
  allowExec: boolean;
  allowInteractiveShell: false;
  confirmationMode: 'always' | 'destructive' | 'never';
  allowedRoots: string[];
}

export interface RemoteConnection {
  id: ConnectionId;
  name: string;
  folderId: FolderId | null;
  order: number;
  host: string;
  port: number;
  username: string;
  defaultRemotePath: string;
  authentication: Authentication;
  importedFromSshConfig?: { sourcePath: string; hostPattern: string };
  agentAccess: AgentAccessPolicy;
  options: {
    keepAliveIntervalMs?: number;
    keepAliveCountMax?: number;
    readyTimeoutMs?: number;
  };
  createdAt: number;
  updatedAt: number;
}

export interface ConnectionFolder {
  id: FolderId;
  name: string;
  parentId: FolderId | null;
  order: number;
  createdAt: number;
  updatedAt: number;
}

export interface TrustedHostKey {
  hostIdentity: string;
  algorithm: string;
  sha256Fingerprint: string;
  firstTrustedAt: number;
  lastSeenAt: number;
}

export interface UiPreferences {
  expandedFolderIds: string[];
}

export interface PersistedStateV1 {
  schemaVersion: 1;
  connections: RemoteConnection[];
  folders: ConnectionFolder[];
  hostKeys: TrustedHostKey[];
  uiPreferences: UiPreferences;
}

export interface ConnectionSummary {
  readonly id: ConnectionId;
  readonly label: string;
}

export const defaultAgentAccessPolicy = (): AgentAccessPolicy => ({
  enabled: false,
  allowReadFiles: false,
  allowWriteFiles: false,
  allowExec: false,
  allowInteractiveShell: false,
  confirmationMode: 'always',
  allowedRoots: [],
});

export const emptyPersistedState = (): PersistedStateV1 => ({
  schemaVersion: 1,
  connections: [],
  folders: [],
  hostKeys: [],
  uiPreferences: { expandedFolderIds: [] },
});
